package main

import (
	"cmp"
	"context"
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/crgimenes/hostd/service"
)

// runCaddyfile writes a Caddyfile from the declarations and stops there. It
// does not install it anywhere and never talks to a machine: the file belongs
// beside the declaration that produced it, in the operator's tree, where push
// carries it like any other artifact and where a hand can edit it.
//
// hostd renders nothing at runtime. That is the whole point of generating to
// stdout — what runs is the file somebody looked at and committed, not a
// template evaluated on a machine at three in the morning.
func runCaddyfile(ctx context.Context, opt options, args []string) (int, error) {
	if len(args) > 0 {
		return exitUsage, fmt.Errorf("caddyfile takes no arguments; it reads the declarations in %s", opt.config)
	}
	// The answer is a Caddyfile, not one of hostd's own. Rendering it as JSON
	// would be answering a different question than the one asked.
	if opt.filoOut || opt.jsonOut {
		return exitUsage, fmt.Errorf("caddyfile writes a Caddyfile, so -filo and -json do not apply to it")
	}
	// The TREE, not a services directory: LoadDir is for what a machine holds,
	// where every .filo is a service. The tree also has inventory.filo and
	// services that are directories, so LoadDir read the inventory as a broken
	// service and never saw a directory service at all — found the day the
	// first directory service declared a domain.
	declarations, err := service.LoadTree(ctx, opt.config)
	if err != nil {
		return exitFailed, err
	}
	declared := make([]service.Service, 0, len(declarations))
	for _, held := range declarations {
		declared = append(declared, held.Service)
	}
	// Every service the tree describes with a domain. Where a service RUNS is
	// not in the tree any more — it is a per-machine decision — and this
	// command deliberately needs no machine to be reachable, so it cannot know
	// and does not guess. What comes out is a file to redirect and then edit,
	// which is what it always was.
	out, err := caddyfile(declared, opt.config, opt.host)
	if err != nil {
		return exitFailed, err
	}
	if out == "" {
		// Nothing on stdout, deliberately. This command is written to be
		// redirected over a file that is serving traffic, and an empty one
		// would take a working proxy down without a word.
		return exitFailed, fmt.Errorf("no declaration in %s names a domain, so there is nothing to serve", opt.config)
	}
	_, _ = io.WriteString(opt.out, out)
	return exitOK, nil
}

type site struct {
	domains  []string
	upstream string
	service  string
}

// caddyfile is pure so that what it writes can be read in a test rather than
// on a machine. It answers "" when nothing declares a domain: an empty
// Caddyfile is a decision the caller has to make, not one to make for them.
func caddyfile(declared []service.Service, source, host string) (string, error) {
	sites := make([]site, 0, len(declared))
	for _, svc := range declared {
		if len(svc.Domain) == 0 {
			continue
		}
		domains := slices.Clone(svc.Domain)
		slices.Sort(domains)
		sites = append(sites, site{domains: domains, upstream: svc.Upstream(), service: svc.Name})
	}
	if len(sites) == 0 {
		return "", nil
	}
	// Sorted, because this file is committed: a regeneration that reorders
	// blocks would show up as a change nobody made, and the diff is how anyone
	// reviews what a generator did.
	slices.SortFunc(sites, func(a, b site) int {
		return cmp.Or(strings.Compare(a.domains[0], b.domains[0]), strings.Compare(a.service, b.service))
	})
	err := oneOwnerPerDomain(sites)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by hostctl caddyfile from the declarations in %s.\n", source)
	if host != "" {
		fmt.Fprintf(&b, "# For %s: only what the tree places there is here.\n", host)
	}
	// Said plainly, because the alternative was hostd rendering this on the
	// machine and that was rejected: what runs is the file in the tree.
	b.WriteString("# It is an ordinary file from here on. Edit it by hand if you need to;\n")
	b.WriteString("# nothing regenerates it, and hostd only carries what is beside the\n")
	b.WriteString("# declaration.\n")
	for _, one := range sites {
		fmt.Fprintf(&b, "\n%s {\n", strings.Join(one.domains, ", "))
		fmt.Fprintf(&b, "\treverse_proxy %s\n", one.upstream)
		b.WriteString("}\n")
	}
	return b.String(), nil
}

// Two services answering for one name is a file whose behaviour depends on
// which block Caddy reads last. Refusing names both, because the operator has
// to decide which one is wrong.
func oneOwnerPerDomain(sites []site) error {
	owner := make(map[string]string)
	for _, one := range sites {
		for _, domain := range one.domains {
			held, taken := owner[domain]
			if taken {
				return fmt.Errorf("%s is declared by both %s and %s; one name cannot reach two services", domain, held, one.service)
			}
			owner[domain] = one.service
		}
	}
	return nil
}
